import Vue from 'vue'
import VueRouter from 'vue-router'
Vue.use(VueRouter)


       import alertCOM from '../components/alertCOM.vue'
import aspectCOM from '../components/aspectCOM.vue'
import avatarCOM from '../components/avatarCOM.vue'
import badgeCOM from '../components/badgeCOM.vue'
import breadcrumbCOM from '../components/breadcrumbCOM.vue'
import buttonCOM from '../components/buttonCOM.vue'
import buttonGroupCOM from '../components/buttonGroupCOM.vue'
import buttonToolbarCOM from '../components/buttonToolbarCOM.vue'
import calendarCOM from '../components/calendarCOM.vue'
import cardCOM from '../components/cardCOM.vue'
import carouselCOM from '../components/carouselCOM.vue'
import collapseCOM from '../components/collapseCOM.vue'
import dropdownCOM from '../components/dropdownCOM.vue'
import embedCOM from '../components/embedCOM.vue'
import formCOM from '../components/formCOM.vue'
import formCheckboxCOM from '../components/formCheckboxCOM.vue'
import formDatepickerCOM from '../components/formDatepickerCOM.vue'
import formFileCOM from '../components/formFileCOM.vue'
import formGroupCOM from '../components/formGroupCOM.vue'
import formInputCOM from '../components/formInputCOM.vue'
import formRadioCOM from '../components/formRadioCOM.vue'
import formRatingCOM from '../components/formRatingCOM.vue'
import formSelectCOM from '../components/formSelectCOM.vue'
import formSpinbuttonCOM from '../components/formSpinbuttonCOM.vue'
import formTagsCOM from '../components/formTagsCOM.vue'
import formTextareaCOM from '../components/formTextareaCOM.vue'
import formTimepickerCOM from '../components/formTimepickerCOM.vue'
import imageCOM from '../components/imageCOM.vue'
import inputGroupCOM from '../components/inputGroupCOM.vue'
import jumbotronCOM from '../components/jumbotronCOM.vue'
import layoutCOM from '../components/layoutCOM.vue'
import linkCOM from '../components/linkCOM.vue'
import listGroupCOM from '../components/listGroupCOM.vue'
import mediaCOM from '../components/mediaCOM.vue'
import modalCOM from '../components/modalCOM.vue'
import navCOM from '../components/navCOM.vue'
import navbarCOM from '../components/navbarCOM.vue'
import overlayCOM from '../components/overlayCOM.vue'
import paginationCOM from '../components/paginationCOM.vue'
import paginationNavCOM from '../components/paginationNavCOM.vue'
import popoverCOM from '../components/popoverCOM.vue'
import progressCOM from '../components/progressCOM.vue'
import sidebarCOM from '../components/sidebarCOM.vue'
import spinnerCOM from '../components/spinnerCOM.vue'
import tableCOM from '../components/tableCOM.vue'
import tabsCOM from '../components/tabsCOM.vue'
import timeCOM from '../components/timeCOM.vue'
import toastCOM from '../components/toastCOM.vue'
import tooltipCOM from '../components/tooltipCOM.vue'
import hoverDIR from '../components/hoverDIR.vue'
import popoverDIR from '../components/popoverDIR.vue'
import scrollspyDIR from '../components/scrollspyDIR.vue'
import toggleDIR from '../components/toggleDIR.vue'
import tooltipDIR from '../components/tooltipDIR.vue'
import visibleDIR from '../components/visibleDIR.vue'
       const routes = [{path: '/alertCOM', component: alertCOM},{path: '/aspectCOM', component: aspectCOM},{path: '/avatarCOM', component: avatarCOM},{path: '/badgeCOM', component: badgeCOM},{path: '/breadcrumbCOM', component: breadcrumbCOM},{path: '/buttonCOM', component: buttonCOM},{path: '/buttonGroupCOM', component: buttonGroupCOM},{path: '/buttonToolbarCOM', component: buttonToolbarCOM},{path: '/calendarCOM', component: calendarCOM},{path: '/cardCOM', component: cardCOM},{path: '/carouselCOM', component: carouselCOM},{path: '/collapseCOM', component: collapseCOM},{path: '/dropdownCOM', component: dropdownCOM},{path: '/embedCOM', component: embedCOM},{path: '/formCOM', component: formCOM},{path: '/formCheckboxCOM', component: formCheckboxCOM},{path: '/formDatepickerCOM', component: formDatepickerCOM},{path: '/formFileCOM', component: formFileCOM},{path: '/formGroupCOM', component: formGroupCOM},{path: '/formInputCOM', component: formInputCOM},{path: '/formRadioCOM', component: formRadioCOM},{path: '/formRatingCOM', component: formRatingCOM},{path: '/formSelectCOM', component: formSelectCOM},{path: '/formSpinbuttonCOM', component: formSpinbuttonCOM},{path: '/formTagsCOM', component: formTagsCOM},{path: '/formTextareaCOM', component: formTextareaCOM},{path: '/formTimepickerCOM', component: formTimepickerCOM},{path: '/imageCOM', component: imageCOM},{path: '/inputGroupCOM', component: inputGroupCOM},{path: '/jumbotronCOM', component: jumbotronCOM},{path: '/layoutCOM', component: layoutCOM},{path: '/linkCOM', component: linkCOM},{path: '/listGroupCOM', component: listGroupCOM},{path: '/mediaCOM', component: mediaCOM},{path: '/modalCOM', component: modalCOM},{path: '/navCOM', component: navCOM},{path: '/navbarCOM', component: navbarCOM},{path: '/overlayCOM', component: overlayCOM},{path: '/paginationCOM', component: paginationCOM},{path: '/paginationNavCOM', component: paginationNavCOM},{path: '/popoverCOM', component: popoverCOM},{path: '/progressCOM', component: progressCOM},{path: '/sidebarCOM', component: sidebarCOM},{path: '/spinnerCOM', component: spinnerCOM},{path: '/tableCOM', component: tableCOM},{path: '/tabsCOM', component: tabsCOM},{path: '/timeCOM', component: timeCOM},{path: '/toastCOM', component: toastCOM},{path: '/tooltipCOM', component: tooltipCOM},{path: '/hoverDIR', component: hoverDIR},{path: '/popoverDIR', component: popoverDIR},{path: '/scrollspyDIR', component: scrollspyDIR},{path: '/toggleDIR', component: toggleDIR},{path: '/tooltipDIR', component: tooltipDIR},{path: '/visibleDIR', component: visibleDIR}]
    

const router = new VueRouter({
  routes
})

export default router
